### ISSUE TITLE
Led file rename

### ISSUE THREAD

**Issue by jlauha** [rameplayerorg/rameplayer-backend#27]
"RAME" led in proto r2kbd is orange, but it's blue on final devices. Do we want to rename it? (needs to be changed in both backend and device tree)

**Comment by fabled** [comment]
I'd rather remove the led color from the name. Yes, the docs recommend it. But in practice very few include the color since sometimes the color can be changed between hardware builds... I think none of the upstream led names contain the led color in the led name.

**Comment by jlauha** [comment]
Thanks for the comment, I agree. Removed color from the led filenames with the two linked commits (alpine/backend repos).
