### ISSUE TITLE
USB sticks are read (remounted) differently when booting vs when hot-plugging in

### ISSUE THREAD

**Issue by jlauha** [rameplayerorg/rameplayer-backend#36]
Steps to reproduce:
1. Put files with unusual characters in filenames to USB stick (e.g. filename containing partly arabic characters, or maybe just some with umlauts like test_äö.mp4).
2. Put stick to player and reboot it.
3. See files listed in WebUI (or also in local ui, but possibily with missing glyphs as the font doesn't have full set of unicode chars)
4. Detach USB stick and put it back to the player.
5. Note how any media files with unusual characters in filenames are now missing from the file listing.

Possible cause:
When booting, USB stick is apparently mounted with utf8 IO charset (/log shows warning about that as not being recommended for FAT). When re-plugging same USB stick back in, no similar warning is listed in the log.
The "RAME: Scanning file:////..." entries for weird filenames are present in log for the first listing (boot), but missing for second time.

**Comment by viliman** [comment]
@jlauha can you try a fix for this?
