### ISSUE TITLE
Stream pause cannot be resumed

### ISSUE THREAD

**Issue by jlauha** [rameplayerorg/rameplayer-backend#42]
If rtmp stream is paused, player goes to "0:00" state (with buffering status icon in local ui). That state cannot be resumed, it can only be stopped. However same stream can be continued after stopping by simply starting to play it again.

**Comment by fabled** [comment]
Maybe we should disable pause state for live streams. The server side can even drop paused clients. This applies mostly to rtmp. HLS based stuff should just work.
