### ISSUE TITLE
Player status drops to "buffering" when playing live stream for long time

### ISSUE THREAD

**Issue by jlauha** [rameplayerorg/rameplayer-backend#43]
It seems that after over 9 hours of live streaming, the player drops to "buffering" state.

This has been observed at least 3 times to be just a bit over 9 hours.
Here's a log of 2 such runs, obtained by adding simple debug log call to mprisplayer.log plugin (prints new player status whenever it changes):

May  6 17:44:34 rame user.debug RAME: mprisplayer status changed to: playing
May  7 02:47:20 rame user.debug RAME: mprisplayer status changed to: buffering
(difference: 9 hours 2 minutes 46 seconds)

May  7 06:08:32 rame user.debug RAME: mprisplayer status changed to: playing
May  7 15:11:40 rame user.debug RAME: mprisplayer status changed to: buffering
(difference: 9 hours 3 minutes 8 seconds)

The difference is not exactly the same, but quite close. Note that the amounts are suspiciously almost 32767 seconds (signed 16bit int max). (Wild guess: perhaps this issue happens when buffered amount wraps over 32767 seconds?)

**Comment by viliman** [comment]
Good Catch @jlauha !

**Comment by jlauha** [comment]
New test round:
May  7 15:25:05 rame user.debug RAME: mprisplayer status changed to: playing
May  8 00:29:10 rame user.debug RAME: mprisplayer status changed to: buffering
(9h 4min 5sec = 32645 seconds)

**Comment by jlauha** [comment]
Took until now to check this against the theory:
mprisplayer.lua row 45 "if position >= 0 then", after that in else...end is the code which goes to buffering state (and sets position to 0 since it was apparently negative).
So apparently the omx starts returning negative position through DBus API.

**Comment by fabled** [comment]
dbus-monitor says:

```
method call time=263791.461307 sender=:1.0 -> destination=org.mpris.MediaPlayer2.omxplayer serial=1210215 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=PlaybackStatus
error time=263791.462134 sender=org.freedesktop.DBus -> destination=:1.0 error_name=org.freedesktop.DBus.Error.LimitsExceeded reply_serial=1210215
   string "The maximum number of pending replies per connection has been reached"
```

Need to investigate more.

**Comment by fabled** [comment]
Seems to be omxplayer issue. Somehow it just stops answering to D-BUS messages:

```
# dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Position
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by fabled** [comment]
dbus-monitor says at time of failure:

```
method call time=308935.741426 sender=:1.0 -> destination=org.mpris.MediaPlayer2.omxplayer serial=1633004 path=/org/mpris/MediaPlayer2; interface=
org.freedesktop.DBus.Properties; member=PlaybackStatus
method return time=308935.760843 sender=:1.423 -> destination=:1.0 serial=375340 reply_serial=1633004
   string "Playing"
method call time=308935.762178 sender=:1.0 -> destination=org.mpris.MediaPlayer2.omxplayer serial=1633005 path=/org/mpris/MediaPlayer2; interface=
org.freedesktop.DBus.Properties; member=Position
method return time=308935.786234 sender=:1.423 -> destination=:1.0 serial=375341 reply_serial=1633005
   int64 34197208688
method call time=308935.787704 sender=:1.0 -> destination=org.mpris.MediaPlayer2.omxplayer serial=1633006 path=/org/mpris/MediaPlayer2; interface=
org.freedesktop.DBus.Properties; member=Duration
method return time=308935.806821 sender=:1.423 -> destination=:1.0 serial=375342 reply_serial=1633006
   int64 34197880000
method call time=308936.007861 sender=:1.0 -> destination=org.mpris.MediaPlayer2.omxplayer serial=1633007 path=/org/mpris/MediaPlayer2; interface=
org.freedesktop.DBus.Properties; member=PlaybackStatus
method call time=308937.210076 sender=:1.0 -> destination=org.mpris.MediaPlayer2.omxplayer serial=1633008 path=/org/mpris/MediaPlayer2; interface=
org.freedesktop.DBus.Properties; member=PlaybackStatus
method call time=308938.412397 sender=:1.0 -> destination=org.mpris.MediaPlayer2.omxplayer serial=1633009 path=/org/mpris/MediaPlayer2; interface=
org.freedesktop.DBus.Properties; member=PlaybackStatus
```

Basically, omxplayer just stops responding. Not sure if it's omxplayer or libdbus issues. strace of omxplayer does imply that it polls for the d-bus connection, but does not read from it. This implies issue being likely in libdbus.

**Comment by fabled** [comment]
Fixed with: http://git.alpinelinux.org/cgit/aports/commit/?id=83bb4f23dc439c99df6dc39abb8626631f705e48

Fix submitted upstream: https://github.com/popcornmix/omxplayer/pull/465
