### ISSUE TITLE
Backend support html help files

### ISSUE THREAD

**Issue by viliman** [rameplayerorg/rameplayer-backend#47]
There is need to support html help files from backend to user

**Comment by jlauha** [comment]
(status update after some discussion) - will/should be done just by adding static help/index.html to be part of webui.

**Comment by jlauha** [comment]
As the help will be done entirely in webui side (static pages or with angular ui tour), this can be closed.
=> https://github.com/rameplayerorg/rameplayer-webui/issues/33
