### ISSUE TITLE
Regression - File upload does not work

### ISSUE THREAD

**Issue by jlauha** [rameplayerorg/rameplayer-backend#66]
At some point File upload feature has stopped working.

When trying to upload file, backend correctly gets file name and possibly part of it. MIME type is accepted, and also the file goes through ffprobe after a short while.

However, after a few seconds this error is printed:
/usr/share/lua/5.3/cqueues/socket.lua:390: exceeded unchecked error limit (Operation timed out)

It seems like the upload is tried again (?), because after waiting for 10-20 seconds, the same thing happens again.

**Comment by foilharp** [comment]
This is a problem of a current development version, but not a problem on the stable firmware version 1.3.3

**Comment by jlauha** [comment]
This seems to be corrected just by fixing issues in autobuild.
